version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
  db:
    image: mysql:5.7
    # volumes:
    #   - db_data:/var/lib/mysql
    # restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: password
    #   MYSQL_DATABASE: mpower_dev
    #   MYSQL_USER: mpower_dev
    #   MYSQL_PASSWORD: password
volumes:
    db_data:
