version: '3'
services:
  web:
    build: .
    ports:
     - "8080:5000"
    volumes:
     - .:/code
    links:
     - db:mysql
    container_name: mpower_api_app_1
    depends_on:
     - db
  db:
    image: mysql:5.7
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    container_name: mpower_api_db_1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mpower_api

