FROM mysql:5.7

ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_DATABSE mpower_api
ENV MYSQL_USER mpower
ENV MYSQL_PASSWORD mpower

# COPY initdb.sql /docker-entrypoint-initdb.d/db.sql
# COPY my.cnf /etc/mysql/my.cnf
# RUN /entrypoint.sh mysqld & sleep 30 && killall mysqld
# RUN rm /docker-entrypoint-initdb.d/db.sql
